[project]
name = "uniform-detection-server"
version = "1.0.0"
description = "dsdfgdf"
dependencies = [
    "flask","facenet_pytorch","ultralytics", "Pillow"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"